package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/jakebromberg/code-audit-pipeline/internal/diffmatch"
	"github.com/jakebromberg/code-audit-pipeline/internal/frontmatter"
	"github.com/jakebromberg/code-audit-pipeline/internal/render"
)

// touchedSet is the parsed --touched payload: a set of normalized
// repo-relative paths. Paths are normalized via diffmatch.NormalizePath
// (Go port of extractors/typescript/_lib/walk-predicate.mjs:34 normalizePath)
// so they compare byte-equal against catalog `.file` entries.
type touchedSet map[string]struct{}

// loadTouchedSet reads --touched <path>, expects a JSON array of strings,
// normalizes each entry. Validation rules:
//   - File missing/unreadable: returns error (caller exits 2 — usage error).
//   - JSON parse failure: returns error (caller exits 2).
//   - Top-level value is not an array: returns error (caller exits 2).
//   - Any element is not a string: returns error citing the offending index.
//   - Empty array: returns an empty (non-nil) set. The renderer treats this
//     as "no files touched" — every cluster is filtered out and the
//     "no structural impact" body is emitted.
//
// Caller errors fail loud (exit 2) so the workflow author fixes the
// resolve-touched.sh step rather than the comment surface silently
// degrading.
func loadTouchedSet(path string) (touchedSet, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("--touched %s: %w", path, err)
	}
	var raw []any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("--touched %s: parse JSON: %w", path, err)
	}
	set := make(touchedSet, len(raw))
	for i, v := range raw {
		s, ok := v.(string)
		if !ok {
			return nil, fmt.Errorf("--touched %s: element [%d] is %T, want string", path, i, v)
		}
		n := diffmatch.NormalizePath(s)
		if n == "" {
			continue
		}
		set[n] = struct{}{}
	}
	return set, nil
}

// filterRowsByTouched drops cluster rows where no member's
// touched_in_window is true AND no member's normalized .file is in the
// touched set. Pair and metric shapes pass through unchanged: pair
// queries are two-document joins (the touched-side already gates them);
// the touched-window-debt-summary metric self-filters via its own
// members[].
//
// touched == nil short-circuits to pass-through — the caller did not
// pass --touched, so no filtering is requested.
//
// The header's shape field is the source of truth for shape; we treat
// any non-cluster shape as pass-through.
func filterRowsByTouched(rows []render.Row, header *frontmatter.Header, touched touchedSet) []render.Row {
	if touched == nil {
		return rows
	}
	if header == nil || !shapeContains(header.Shape, "cluster") {
		return rows
	}
	out := make([]render.Row, 0, len(rows))
	for _, row := range rows {
		if clusterRowIsTouched(row, touched) {
			out = append(out, row)
		}
	}
	return out
}

// shapeContains reports whether the declared shape list includes target.
// The frontmatter.Header.Shape is a slice; cluster queries list "cluster".
func shapeContains(shapes []string, target string) bool {
	for _, s := range shapes {
		if s == target {
			return true
		}
	}
	return false
}

// clusterRowIsTouched returns true if any cluster member has
// touched_in_window=true or has a normalized .file in the touched set.
func clusterRowIsTouched(row render.Row, touched touchedSet) bool {
	rawMembers, ok := row["members"].([]any)
	if !ok {
		return false
	}
	for _, m := range rawMembers {
		mm, ok := m.(map[string]any)
		if !ok {
			continue
		}
		if t, _ := mm["touched_in_window"].(bool); t {
			return true
		}
		if f, _ := mm["file"].(string); f != "" {
			if _, hit := touched[diffmatch.NormalizePath(f)]; hit {
				return true
			}
		}
	}
	return false
}

// prCommentOpts is the comment-mode composition configuration. Populated
// from CLI flags by Report().
type prCommentOpts struct {
	marker       string
	sizeCapBytes int
}

// composePRComment renders the per-PR comment body. Differs from
// composeReport in five ways:
//
//  1. Sticky marker line as the first line (so marocchino's `header:`
//     substring scan matches).
//  2. No "Generated by code-audit …" timestamp/version header — the
//     comment is updated in place across force-pushes; a timestamp would
//     thrash the marocchino diff check every run.
//  3. No "Skipped queries" footer — runtime errors that landed queries in
//     the skipped list are not actionable from the PR-comment surface.
//     They go to stderr (the runner log) instead.
//  4. Per-section size cap: when the running byte count would exceed
//     sizeCapBytes after appending a section, the section is dropped and
//     a truncation footer is emitted. No section is partially rendered.
//  5. Empty-results path: when no section produced any rows (e.g. every
//     cluster was filtered out by --touched), the body is the marker line
//     plus a "no structural impact" notice so the sticky comment still
//     updates and reads sensibly.
//
// Sections render in deterministic query-name order (alphabetical,
// matching listQueries). Given identical inputs, the output is byte-
// reproducible.
//
// Caller is responsible for the fail-quiet exit path (see Report()).
func composePRComment(results []sectionResult, opts prCommentOpts) string {
	marker := opts.marker
	if marker == "" {
		marker = "code-audit-pipeline-v1"
	}
	capBytes := opts.sizeCapBytes
	if capBytes <= 0 {
		capBytes = 60000
	}

	// Render each non-skipped section to a string, in deterministic order.
	sort.SliceStable(results, func(i, j int) bool { return results[i].name < results[j].name })

	header := fmt.Sprintf("<!-- %s -->\n\n", marker)

	var rendered []sectionRender
	for _, r := range results {
		if r.err != nil || r.skipped != "" || len(r.blocks) == 0 {
			continue
		}
		var sec strings.Builder
		fmt.Fprintf(&sec, "## %s\n\n", r.name)
		desc := strings.TrimRight(r.header.Desc, ".")
		shape := strings.Join(r.header.Shape, ", ")
		fmt.Fprintf(&sec, "_%s. %d row(s), shape: %s._\n\n", desc, len(r.blocks), shape)
		for _, block := range r.blocks {
			sec.WriteString(block)
			sec.WriteString("\n")
		}
		rendered = append(rendered, sectionRender{name: r.name, body: sec.String()})
	}

	if len(rendered) == 0 {
		return header + "_No structural impact: no cluster contains a file touched by this PR._\n"
	}

	var b strings.Builder
	b.WriteString(header)

	used := len(header)
	kept := 0
	dropped := 0
	for _, sec := range rendered {
		if used+len(sec.body) > capBytes {
			dropped++
			continue
		}
		b.WriteString(sec.body)
		used += len(sec.body)
		kept++
	}

	if dropped > 0 {
		footer := fmt.Sprintf("\n> +%d more section(s) omitted to stay under the %d-byte comment cap. See workflow run logs for the full report.\n", dropped, capBytes)
		b.WriteString(footer)
	}

	if kept == 0 {
		// Pathological case — every section was individually larger than
		// the cap. Replace the body with the cap-overrun notice so the
		// comment still reads sensibly.
		return header + fmt.Sprintf("> code-audit: every report section exceeded the %d-byte cap individually; see workflow logs.\n", capBytes)
	}

	return b.String()
}

// sectionRender is a per-section rendered body + name pair, accumulated
// before the size-cap pass.
type sectionRender struct {
	name string
	body string
}

// failQuietBody is the comment body emitted in --mode pr-comment
// --on-extraction-failure quiet when one or more upstream pipeline
// errors occurred. detectedLanguages may be empty.
func failQuietBody(marker string, detectedLanguages []string) string {
	if marker == "" {
		marker = "code-audit-pipeline-v1"
	}
	langs := strings.Join(detectedLanguages, ", ")
	if langs == "" {
		langs = "<unknown>"
	}
	return fmt.Sprintf(
		"<!-- %s -->\n\n> code-audit: extraction failed for %s; see workflow run logs.\n",
		marker, langs,
	)
}
