"""Shared helpers for the Python extractor (paths, hashing, walking, AST utilities).

Keep this module dependency-free (stdlib only) so the extractor stays bootstrap-free.
"""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

SCHEMA_VERSION = "2.0"
FINGERPRINT_V = "shape_sig:1"
LANGUAGE = "python"
EXTRACTOR_VERSION = "0.1.0"

# Directories skipped on every walk. Mirrors the substrate convention in
# docs/pipeline-contract.md §"What to skip" plus Python-specific noise.
SKIP_DIRS = frozenset({
    "node_modules", "dist", "build", "coverage",
    "__pycache__", ".venv", ".tox", ".eggs",
})

# Test-path directory segments — universal patterns from docs/pipeline-contract.md
# §"Test path patterns".
TEST_DIR_SEGMENTS = frozenset({
    "tests", "test", "__tests__", "__test__",
    "spec", "__mocks__", "__fixtures__", "fixtures", "e2e",
})

# Test-filename patterns (Python-specific + universal). Per the contract,
# language-specific extensions are MUST-when-applicable.
_TEST_FILENAME_RE = re.compile(
    r"^(test_.+\.py|.+_test\.py|conftest\.py)$"
    r"|^.+\.(test|spec|fixture|fixtures|mock|mocks)\.py$"
)


def is_test_path(rel_path: str) -> bool:
    """Path-based test-file classification. Mirrors the universal contract."""
    parts = rel_path.split(os.sep)
    for seg in parts[:-1]:
        if seg in TEST_DIR_SEGMENTS:
            return True
    return bool(_TEST_FILENAME_RE.match(parts[-1]))


def is_generated(rel_path: str) -> bool:
    """File-path-derived generated-flag. Mirrors the substrate convention."""
    # Any path segment named `generated` flips the flag — matches the TS rule
    # `(^|\/)generated\//`. The `.egg-info/` directory and `_pb2.py` (protobuf)
    # outputs are also generated by convention.
    norm = rel_path.replace(os.sep, "/")
    if "/generated/" in norm or norm.startswith("generated/"):
        return True
    if ".egg-info/" in norm or norm.endswith(".egg-info"):
        return True
    if norm.endswith("_pb2.py") or norm.endswith("_pb2_grpc.py"):
        return True
    return False


def walk_python_files(root: Path):
    """Yield every .py file under root, applying the skip-list (dotdirs +
    SKIP_DIRS). Directory prune is in-place so we don't descend into clones."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith(".") and d not in SKIP_DIRS
        ]
        for fn in filenames:
            if fn.endswith(".py"):
                yield Path(dirpath) / fn


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def shape_sig(fields: list[str]) -> str:
    """shape_sig = fields.sorted().join('|').lower() — per pipeline-contract.md."""
    return "|".join(sorted(fields)).lower()


def normalize_type_text(text: str) -> str:
    """Collapse whitespace runs, trim — used to normalize annotation source."""
    return re.sub(r"\s+", " ", text).strip()


def annotation_text(node: ast.AST | None) -> str:
    """Render an AST annotation node as source. None / unparseable -> 'Any'."""
    if node is None:
        return "Any"
    try:
        return normalize_type_text(ast.unparse(node))
    except Exception:
        return "Any"


def compute_source_sha(extractor_dir: Path) -> str:
    """Resolve the SHA of the extractor's source tree.

    Walks up from extractor_dir looking for the first ancestor whose
    `git rev-parse --show-toplevel` equals itself. Stops at $HOME or fs root.
    Mirrors the TS extractor's logic from extractors/typescript/type-catalog.mjs.
    Returns 'unknown' (with a stderr warning) if not in a git checkout.
    """
    try:
        home = Path(os.path.expanduser("~")).resolve()
    except Exception:
        home = Path(os.path.expanduser("~"))
    try:
        cur = extractor_dir.resolve()
    except Exception:
        cur = extractor_dir
    env = {**os.environ, "GIT_TERMINAL_PROMPT": "0"}
    for _ in range(16):
        if not cur or str(cur) == str(home):
            break
        try:
            res = subprocess.run(
                ["git", "rev-parse", "--show-toplevel"],
                cwd=str(cur), env=env, capture_output=True, text=True, timeout=2.0,
            )
            if res.returncode == 0:
                top = Path(res.stdout.strip())
                if top == cur:
                    head = subprocess.run(
                        ["git", "rev-parse", "HEAD"],
                        cwd=str(cur), env=env, capture_output=True, text=True, timeout=2.0,
                    )
                    sha = head.stdout.strip()
                    if re.fullmatch(r"[0-9a-f]{40}", sha):
                        return sha
                    break
        except Exception:
            pass
        parent = cur.parent
        if parent == cur:
            break
        cur = parent
    import sys
    sys.stderr.write(
        'warning: extractor source not in a git checkout; source_sha recorded as "unknown"\n'
    )
    return "unknown"


def make_extractor_block(name: str, source_sha: str) -> dict:
    return {
        "language": LANGUAGE,
        "name": name,
        "version": EXTRACTOR_VERSION,
        "source_sha": source_sha,
    }


def write_catalog(output_path: str | None, payload: dict):
    """Either write JSON to a path or stream to stdout."""
    import sys
    text = json.dumps(payload, indent=2, ensure_ascii=False)
    if output_path:
        Path(output_path).write_text(text + "\n", encoding="utf-8")
        sys.stderr.write(f"Wrote {output_path}\n")
    else:
        sys.stdout.write(text)
